### PR TITLE
Docker image

### PR DESCRIPTION
**Pull request by wiktorn**
All details in README-Dockerfile.

Dockerfile creates standalone image that start Relation Analyzer. docker-compose - adds the database.

The only thing that's missing, is the initialization of the database, but I wasn't sure, if executing [src/main/schema/test-data.sql](https://github.com/grundid/relation-analyzer/blob/master/src/main/schema/test-data.sql) would be enough (for a "production" use).

### CODE REVIEW

**Comment by wiktorn** [comment]
There is one thing still worth correcting. `/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/config.properties` will grow with each subsequent start of the same container.

I didn't want to overwrite this file as there are some values generated by Maven. Do you have any ideas, how to separate this two things?

Also worth noting - it would be nice if Overpass / OpenStreetMap API URL's would be also configurable in environment

**Comment by grundid** [comment]
Thanks for your contribution. 

You might want to look at the "sed" command to update the config.properties file.

In the last commit I've added the possibility to override the properties in the config file with system properties.
For the Overpass URL we would have to update the osm-tools libraries since the url is hardcoded in this library: https://github.com/grundid/osm-tools

**Comment by wiktorn** [comment]
Maybe the way is just to create a template config.properties file based on what Maven generates and remove all the lines that docker-entrypoint can change.

Then I copy the template and add new lines based on container environment. 

Or - if I understand you correctly - if I set CATALINA_OPTS="-Ddb.username=user" I'll override setting in `config.properties`? This way might be even easier.

What do you think?

**Comment by grundid** [comment]
> CATALINA_OPTS="-Ddb.username=user" 

Yes, this should work with the latest commit

**Comment by wiktorn** [comment]
Done.

**Comment by wiktorn** [comment]
Done

**Comment by grundid** [comment]
Thx. Looks good.

**Pull request merged**
