### PR TITLE
added analyzeRelation/json that returns a JSON instead of an HTML

### PR DESCRIPTION
**Pull request by oxcar**
I added a new method so the path analyzeRelation/json returns a json instead of an html.
This should make easier to automate Relation Analysys.

### CODE REVIEW

**Comment by oxcar** [comment]
Related issue
https://github.com/grundid/relation-analyzer/issues/40

**Comment by grundid** [comment]
Thank you for the PR. I hope the project will build after so many years ;)

**Comment by oxcar** [comment]
I was able to build the docker image with no problems, but locally I was not able.

**Comment by grundid** [comment]
New version (1.5.29) of the relation analyzer is online. The new endpoint seems to be working.

**Comment by oxcar** [comment]
Thank you for the super fast response. Really apreciated.

**Pull request merged**
